disabled_rules:
  - blanket_disable_command
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - opening_brace
  - operator_whitespace
  - redundant_discardable_let
  - trailing_comma
  - type_name
  - unused_closure_parameter
  - xctfail_message

trailing_whitespace:
  ignores_empty_lines: true
