osx_image: xcode10.1
language: swift
cache: bundler
env:
  matrix:
    - platforms=ios
    - platforms=macos
before_install:
  - . Pods/GEContinuousIntegration/travis/before_install
script:
  - . Pods/GEContinuousIntegration/travis/script
after_success:
  - . Pods/GEContinuousIntegration/travis/after_success
