osx_image: xcode10.1
language: swift
env:
  matrix:
    - platform=ios
    - platform=macos
script:
  - pod lib lint --verbose --platforms="${platform:?}"
after_success:
  - bash <(curl -s https://codecov.io/bash)
