osx_image: xcode10.1
language: swift
env:
  matrix:
    - platform=ios
    - platform=macos
script:
  - ddp=$(mktemp -d /tmp/ddp.XXXXX)
  - ./pod-lib-lint-with-coverage "${ddp:?}" --verbose --platforms="${platform:?}"
after_success:
  - bash <(curl -s https://codecov.io/bash) -D "${ddp:?}"
