name: Swift

on:
  push:
    branches:
      - master
      - '**'
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
  linux: # Borrowed from https://github.com/NSHipster/SwiftSyntaxHighlighter/blob/master/.github/workflows/ci.yml
    runs-on: ubuntu-latest
    container:
      image: swift:5.7
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Test
        run: swift test --enable-test-discovery
  lint:
    runs-on: ubuntu-latest
    container:
      image: grigorye/getracing:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: mint run swiftlint
